You-Raouf-je-me-presente/config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/contact', to: 'static_pages#contact', as: 'contact'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/new', to: 'users#new', as: 'new_user'
  post'/new', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'

end

You-Raouf-je-me-presente/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

You-Raouf-je-me-presente/app/models/user.rb
class User < ApplicationRecord
	validates :user_name, 
			uniqueness:true,
			format: { with: /\A[a-zA-Z0-9]+\Z/ }
end

You-Raouf-je-me-presente/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

You-Raouf-je-me-presente/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def about_us
  end

  def about_the_team
  end
end

You-Raouf-je-me-presente/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
  	@user = User.new
  	@user.user_name = params[:username]
  	@user.bio = params[:bio]
  	if @user.save
         redirect_to user_path(@user)
 	else
         render '/users/erreur'
  	end
  end

  def show
  	@user = User.find(params[:id])
  end

end 

You-Raouf-je-me-presente/app/helpers/application_helper.rb
module ApplicationHelper
end

You-Raouf-je-me-presente/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

You-Raouf-je-me-presente/app/helpers/users_helper.rb
module UsersHelper
end

You-Raouf-je-me-presente/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>

    <!-- Balise qui nous permet de rajouter un minimum de CSS. 
    On apprendra plus tard à utiliser bootstrap pour pimper nos sites rapidement. -->

    <title>On se présente</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

You-Raouf-je-me-presente/app/views/static_pages/about.html.erb
<h1>Salut beauté :) </h1>

<p>Tu voulais savoir quoi sur nous ? arrete de nous stalcker stp je vais appeler les flics</p>

You-Raouf-je-me-presente/app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>Salut on a pas envie que tu nous contacte ! on se voit dejà assez souvent sur Slack :)</p>

You-Raouf-je-me-presente/app/views/static_pages/home.html.erb
<h1> Bonjour a tous les amis ! </h1>
<br>
<h1>Bienvenue sur notre page d'accueil de folie</h1>
<p>t'es chaud pour la suite ? allé viens :)</p>

<p>tu veux créer un utilisateur ?  <a href="<%= new_user_path%>"> c'est par ici que ça se passe</a></p>
<br>

<p>Tu veux voir notre About ? <a href="<%=about_path%>"> Allé clique ici mon pote</a></p>


<p>Tu veux nous contacter ? ? <a href="<%=contact_path%>"> Clique here madafackar</a></p>

You-Raouf-je-me-presente/app/views/users/erreur.html.erb
<h1>Eh ! mais tu fais quoi la ?/h1>

<h1>T'es sur la page des naufragés ! sur la page des fameuses peugeot 404 ! hahahah loser va !</h1>

You-Raouf-je-me-presente/app/views/users/new.html.erb
<h1>Ici c'est Paris ! non ici c'est pour créer des utilisateurs, bah ouais kess t'as cru ?</h1>

<p>Allé raméne toi</p> 

 <form action="/new" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  Username: <br>
  <input type="text" name="username"><br>
  
  <textarea name="bio">Ecris quelque chose sur toi </textarea>
  <br>
  <input type="submit" value="Submit">
</form>

You-Raouf-je-me-presente/app/views/users/show.html.erb
<h1> Bienvenue mon pote<%= @user.user_name %></h1>

<p>tu veux savoir quelque chose sur toi ? admire ta bio mon petit <%= @user.bio %> </p>
<br>